Update entrypoint.sh
galexrt/docker-sinusbot pull request #15
Opened 2017-02-22 12:30 UTC by Jormodn

Add Logging Options

2017-02-22 12:54 UTC, galexrt requested changes

2017-02-22 12:54 UTC, galexrt commented on entrypoint.sh
> +if [ "$LOGPATH" == ""]; then
Use use following syntax and put it on line 8.
```
LOGPATH="${LOGPATH:-/sinusbot/data/sinus.log}"
```

2017-02-22 12:54 UTC, galexrt commented on entrypoint.sh
> +LOGPATH="/sinusbot/data/sinus.log"
This is unnecessary when you use the bash like syntax from line 8 comment.

2017-02-22 13:58 UTC, galexrt requested changes
Remove the if condition.
Add a `-` there:
```
LOGPATH="${LOGPATH:-/sinusbot/data/sinus.log}"
```
The `-` is required there.

2017-02-22 14:03 UTC, Jormodn reviewed
Updating Syntax Fails

2017-02-22 14:08 UTC, Jormodn commented
Jetzt zufriden :)

2017-02-22 14:35 UTC, galexrt commented on entrypoint.sh
> +    sed -i 's/LogFile.*/LogFile = $LOGPATH/g' "$SINUS_DIR/config.ini"
Der sed Regex muss es so sein damit die Variable überhaupt aufgelöst wird:
```
's/^LogFile.*/LogFile = '"$LOGPATH"'/g'
```

2017-02-22 14:35 UTC, galexrt requested changes
Ich zitiere:
> Remove the if condition.

;)
Und noch den sed Regex fixen. Dann bin ich zufrieden.

2017-02-22 15:47 UTC, Jormodn reviewed
So ganz ohne If?

2017-02-22 17:44 UTC, galexrt commented
Ja, wäre wahrscheinlich das Beste. Damit Standardmäßig die Logs in das Volume geschrieben werden, wobei ich das eigentlich eher frag würdig finde, da man ja mit `docker logs CONTAINER_NAME_ID` auch die Logs abfragen kann.

2017-02-22 18:17 UTC, galexrt commented
Well, ich werde es jetzt mal mergen. Werde jedoch wahrscheinlich dann irgendwann den default auf `stdout` oder `/dev/null` legen.

2017-02-22 18:17 UTC, galexrt approved these changes

2017-02-22 18:17 UTC, merged

2017-02-22 20:30 UTC, Jormodn commented
Habs jetzt grad getestet und es kommt ein Fehler von der RegEx
sed: -e expression #1, char 25: unknown option to `s'

2017-02-22 20:34 UTC, galexrt commented
Siehe mein Commit.

2017-03-11 21:55 UTC, galexrt commented
@Jormodn As of my recent changes,, the environment variable `LOGPATH` now needs to be given or else the `LogFile` option in Sinusbot won't be set.