Small changes
galexrt/docker-sinusbot pull request #36
Opened 2018-05-09 16:00 UTC by Horstexplorer

Just some small changes in README.md and Dockerfile

2018-05-09 16:06 UTC, galexrt commented on README.md
> +Sinusbot: latest beta (>=0.13.37)
Is the `sinusbot.current.tar.bz2` 0.13.37 or higher?

2018-05-09 16:06 UTC, Horstexplorer commented
TS3-Version 3.1.9 should work with sinusbot too. This could be changed but it doesn't have to.

2018-05-09 16:08 UTC, Horstexplorer commented on README.md
> +Sinusbot: latest beta (>=0.13.37)
Yes it is

2018-05-09 20:01 UTC, galexrt commented
@Horstexplorer If you test that Sinusbot works with TS3 3.1.9 I'm okay with adding in this PR.

2018-05-09 20:02 UTC, galexrt requested changes
One small comment about the README.md change

2018-05-09 20:02 UTC, galexrt commented on README.md
> +**WARNING** There is "no way" to show the password a second time! You can use ```./sinusbot --override-password=newpassword``` to reset the password.
Instead of the triple \` use one instead for a better looking in line code block.

2018-05-09 23:10 UTC, Horstexplorer commented
I checked it, TS3 3.1.9 is working with the current Sinusbot version :)
Sinusbot.current is currently providing 0.13.37-9791176 which seems to be an older build than f7e9ece but since they are using this link everywhere, there shouldn't be any noticeable differences between them.

2018-05-10 06:33 UTC, galexrt requested changes
One last thing, then we are ready to go

2018-05-10 06:33 UTC, galexrt commented on README.md
>  TeamSpeak: 3.1.8 (this version is required for Sinusbot)
Could you update this version number too

2018-05-10 08:41 UTC, galexrt approved these changes

2018-05-10 08:42 UTC, merged

2018-05-10 08:42 UTC, galexrt commented
Thanks for the PR!